Employee_Management/Pages/Employees/Create.cshtml.cs
using Dapper;
using Employee_Management.DataClass;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;

namespace Employee_Management.Pages.Employees
{
    public class CreateModel : PageModel
    {
        public EmployeeInfo employeeInfo = new EmployeeInfo();
        public List<EmployeeInfo> EmployeesList = new List<EmployeeInfo>();

        public readonly IDatabaseConnection Dbc;

        public string errorMessage = "";
        public string successMessage = "";

        public string passwordStrength = "";
        public string temp_pass_strength = "";
        public CreateModel(IDatabaseConnection dbc)
        {
            Dbc= dbc;
        }
       
        public void OnGet()
        {
           
        }
        public async Task OnPost()
        {


            try
            {
                using var connection = Dbc.GetConnection();

                string sql = @"select LoginDetails.Id, Employees.EmployeeNo,Employees.Name,Employees.Email,LoginDetails.Username,
                     LoginDetails.Password
                     from LoginDetails INNER JOIN Employees 
                     ON LoginDetails.EmployeeNo = Employees.EmployeeNo";

                EmployeesList = (List<EmployeeInfo>)(await connection.QueryAsync<EmployeeInfo>(sql));

            }
            catch (Exception ex)
            {
                Console.WriteLine("Exception: " + ex.ToString());
            }


            employeeInfo.EmployeeNo = Request.Form["employeeno"];
            employeeInfo.Name = Request.Form["name"];
            employeeInfo.Email = Request.Form["email"];
            employeeInfo.Username = Request.Form["username"];
            employeeInfo.Password = Request.Form["password"];
            passwordStrength = Request.Form["passwordStrength"];

           // Console.WriteLine("Line 56 ", passwordStrength);
            if(employeeInfo.Username.Length==0 || employeeInfo.Password.Length==0 ||
                employeeInfo.EmployeeNo==null || employeeInfo.Name.Length == 0 || employeeInfo.Email.Length == 0)
            {
                errorMessage = "All fields are required";
                return;
            }

            // save this employee to database

            try
            {
                try
                {

                    foreach (var Employee in EmployeesList)
                    {
                        if (Employee.EmployeeNo == employeeInfo.EmployeeNo)
                        {
                            errorMessage = "This EmployeeNo already exist";
                            return;
                        }
                        if (Employee.Email == employeeInfo.Email)
                        {
                            errorMessage = "This Email already exist";
                            return;
                        }
                        if (Employee.Username == employeeInfo.Username)
                        {
                            errorMessage = "This Username already exist";
                            return;
                        }
                        if (Employee.Password == employeeInfo.Password)
                        {
                            errorMessage = "Password  should be unique";
                            return;
                        }
                    }
                   
                        string temp_password = employeeInfo.Password;
                        
                        int n = temp_password.Length;
                        bool hasLower = false, hasUpper = false,
                                hasDigit = false, specialChar = false;
                        HashSet<char> set = new HashSet<char>(
                            new char[] { '!', '@', '#', '$', '%', '^', '&',
                          '*', '(', ')', '-', '+' });
                        foreach (char i in temp_password.ToCharArray())
                        {
                            if (char.IsLower(i))
                                hasLower = true;
                            if (char.IsUpper(i))
                                hasUpper = true;
                            if (char.IsDigit(i))
                                hasDigit = true;
                            if (set.Contains(i))
                                specialChar = true;
                        }

                        // Strength of password
                        if (hasDigit && hasLower && hasUpper && specialChar && (n >= 10))
                        {
                            temp_pass_strength = "3";
                        }   
                        else if ((hasLower || hasUpper) & specialChar && (n >= 7))
                        {
                            temp_pass_strength = "2";
                        }
                        else if(n>=5)
                        {
                            temp_pass_strength = "1";
                        }  
                        else
                        {
                            errorMessage = "Password Strength must be atleast of 5 length";
                            return;
                        }

                    if (passwordStrength == "1")
                    {
                        if(temp_pass_strength == "1" || temp_pass_strength=="2" || temp_pass_strength == "3")
                        {

                        }
                        else
                        {
                            errorMessage = @"Low Password Strength must be atleast of 5 length";
                            return;
                        }
                    }
                    else if(passwordStrength == "2")
                    {
                        if (temp_pass_strength == "2" || temp_pass_strength == "3")
                        {

                        }
                        else
                        {
                            errorMessage = @" Medium Password Strength must be atleast of 7 length and has atleast 
                                one upperCase or lowerCase and special Character";
                            return;
                        }
                    }
                    else if(passwordStrength == "3")
                    {
                        if (temp_pass_strength == "3")
                        {

                        }
                        else
                        {
                            errorMessage = @"High Password Strength must be atleast of 10 length and has atleast 
                                one upperCase and lowerCase and special Character";
                            return;
                        }
                    }
                    else
                    {
                        errorMessage = "Select PasswordStrength";
                        return;
                    }

                    using var connection = Dbc.GetConnection();
                    string sql1 = @"SET IDENTITY_INSERT Employees ON
                                         INSERT into Employees
                                           (EmployeeNo,Name,Email) Values
                                          (@EmployeeNo,@Name,@Email)
                                           SET IDENTITY_INSERT Employees OFF ";
                    await connection.ExecuteAsync(sql1, new { EmployeeNo = employeeInfo.EmployeeNo, Name = employeeInfo.Name, Email = employeeInfo.Email });

                    string sql = @"INSERT into LoginDetails
                                           (EmployeeNo,Username,Password) Values
                                          (@EmployeeNo,@Username,@Password)";
                    await connection.ExecuteAsync(sql, new {EmployeeNo = employeeInfo.EmployeeNo,Username= employeeInfo.Username,Password = employeeInfo.Password });

                }
                catch (Exception ex)
                {
                    errorMessage=ex.Message;
                    return;
                }

               
               
            }
            catch(Exception ex)
            {
                errorMessage = ex.Message;
                return;
            }


            employeeInfo.EmployeeNo = ""; employeeInfo.Username = ""; employeeInfo.Password = "";
            successMessage = "New employee added correctly";
            Response.Redirect("/Employees/Index");
        }
    }
}

Employee_Management/Pages/Employees/Delete.cshtml.cs
using Dapper;
using Employee_Management.DataClass;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;

namespace Employee_Management.Pages.Employees
{
    public class DeleteModel : PageModel
    {
        public EmployeeInfo employeeinfo = new EmployeeInfo();
        public readonly IDatabaseConnection Dbc;
        public string errorMessage = "";
        public string successMessage = "";
        public DeleteModel(IDatabaseConnection dbc)
        {
            Dbc = dbc;
        }
        public async Task OnGetAsync()
        {
            string Id = Request.Query["Id"];

            try
            {
                using var connection = Dbc.GetConnection();
                var sql1 = @"select LoginDetails.Id,Employees.EmployeeNo,Employees.Name,Employees.Email,
                         LoginDetails.Username,LoginDetails.Password 
                        from LoginDetails Join Employees ON LoginDetails.EmployeeNo = Employees.EmployeeNo 
                       where Id=@Id";
                employeeinfo = await connection.QuerySingleAsync<EmployeeInfo>(sql1, new { Id = Id });

                var sql2 = @"delete from LoginDetails where Id=@Id";
                var sql3 = @"delete from Employees where EmployeeNo=@EmployeeNo";
                var a1 = await connection.ExecuteAsync(sql2, new { Id = employeeinfo.Id });
                var a2 = await connection.ExecuteAsync(sql3, new { EmployeeNo = employeeinfo.EmployeeNo });
            }
            catch (Exception ex)
            { 
                errorMessage=ex.Message;
                return;
            }
            successMessage = "Employee Deleted successfully";
            Response.Redirect("/Employees/Index");
        }
        public void OnPost()
        {
            
        }
    }
}

Employee_Management/Pages/Employees/Index.cshtml.cs
using Dapper;
using Employee_Management.DataClass;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;
using System.Runtime.InteropServices;

namespace Employee_Management.Pages.Employees
{
    public class IndexModel : PageModel
    {
        public List<EmployeeInfo> ListEmployees=new List<EmployeeInfo>();

        [BindProperty]
        public EmployeeInfo EmployeeInfo { get; set; } = new EmployeeInfo();

       public readonly IDatabaseConnection Dbc;
       public IndexModel(IDatabaseConnection dbc)
        {
            Dbc = dbc;
        }

        public async Task OnGetAsync()
        {
            try
            {
                   using var connection = Dbc.GetConnection();
                    
                    string sql = @"select LoginDetails.Id, Employees.EmployeeNo,Employees.Name,Employees.Email,LoginDetails.Username,
                     LoginDetails.Password
                     from LoginDetails INNER JOIN Employees 
                     ON LoginDetails.EmployeeNo = Employees.EmployeeNo"; 

                  ListEmployees = (List<EmployeeInfo>)(await connection.QueryAsync<EmployeeInfo>(sql));

               // ListEmployees = (await connection.QueryAsync<EmployeeInfo>("select * from LoginDetails")).ToList();


            }
            catch(Exception ex)
            {
                Console.WriteLine("Exception: " +  ex.ToString());
            }
        }

        public async Task<IActionResult> OnPostUpdateEmployee()
        {
            using var connection = Dbc.GetConnection();
            string sql2 = @"UPDATE LoginDetails SET Username=@Username, Password=@Password WHERE Id=@Id";
            var a1 = await connection.ExecuteAsync(sql2, new { Username = EmployeeInfo.Username, Password = EmployeeInfo.Password, Id = EmployeeInfo.Id });

            string sql3 = @"UPDATE Employees SET Name=@Name, Email=@Email WHERE EmployeeNo=@EmployeeNo";
            var a2 = await connection.ExecuteAsync(sql3, new { Name = EmployeeInfo.Name, Email = EmployeeInfo.Email, EmployeeNo = EmployeeInfo.EmployeeNo });
            return RedirectToPage();
        }

    }

   
}

Employee_Management/Pages/Employees/Create.cshtml
@page
@model Employee_Management.Pages.Employees.CreateModel

<br />
<h2>New Employee</h2>

@if(Model.errorMessage.Length>0)
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>@Model.errorMessage</strong>
            <button type="button" class="btn-close" data-bs-dismiss="" aria-label="close"></button>
    </div>
}




<!-- Button trigger modal -->
@*<a class='btn btn-primary btn-sm' data-bs-toggle="modal" data-bs-target="#CreateEmployeeModal">Add Employee</a>*@

<!-- Modal -->
@*<div class="modal fade" id="createEmployeeModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title">New Employee</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
 
        <form  action=@Url.Page("/Employees/Create")>
            <div class="row mb-3">
                <label class="col-sm-3 col-form-label">EmployeeNo</label>
                <div class="col-sm-6">
                 <input  type="text" class="form-control" name="employeeno" value="@Model.employeeInfo.EmployeeNo"/>
                </div>
            </div>
             <div class="row mb-3">
                <label class="col-sm-3 col-form-label">Name</label>
                <div class="col-sm-6">
                 <input  type="text" class="form-control" name="name" value="@Model.employeeInfo.Name"/>
                </div>
            </div>
             <div class="row mb-3">
                <label class="col-sm-3 col-form-label">Email</label>
                <div class="col-sm-6">
                 <input  type="text" class="form-control" name="email" value="@Model.employeeInfo.Email"/>
                </div>
            </div>
             <div class="row mb-3">
                <label class="col-sm-3 col-form-label">Username</label>
                <div class="col-sm-6">
                 <input  type="text" class="form-control" name="username" value="@Model.employeeInfo.Username"/>
                </div>
            </div>
            <div  class="row mb-3">
                <label class="col-sm-3 col-form-label">PasswordStrength</label>
                <div class="col-sm-6">
                    <select  class="form-control" name="passwordStrength" >
                        <option value="0" >options</option>
                        <option value="1" >Low</option>
                        <option value="2" >Medium</option>
                        <option value="3" > High</option>
                    </select>
                </div>  
            </div>
             <div class="row mb-3">
                <label class="col-sm-3 col-form-label">Password</label>
                <div class="col-sm-6">
                 <input  type="text" class="form-control" name="password" value="@Model.employeeInfo.Password"/>
                </div>
            </div>

             @if (Model.successMessage.Length > 0)
               {
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                <strong>@Model.successMessage</strong>
                <button type="button" class="btn-close" data-bs-dismiss="" aria-label="close"></button>
                </div>
                }
                
        </form>

      </div>
       <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" data-bs-save="modal">Save</button>
       </div>
      
       
    </div>
  </div>
</div>*@







<form method="post">
    <div class="row mb-3">
        <label class="col-sm-3 col-form-label">EmployeeNo</label>
        <div class="col-sm-6">
         <input  type="text" class="form-control" name="employeeno" value="@Model.employeeInfo.EmployeeNo"/>
        </div>
    </div>
     <div class="row mb-3">
        <label class="col-sm-3 col-form-label">Name</label>
        <div class="col-sm-6">
         <input  type="text" class="form-control" name="name" value="@Model.employeeInfo.Name"/>
        </div>
    </div>
     <div class="row mb-3">
        <label class="col-sm-3 col-form-label">Email</label>
        <div class="col-sm-6">
         <input  type="text" class="form-control" name="email" value="@Model.employeeInfo.Email"/>
        </div>
    </div>
     <div class="row mb-3">
        <label class="col-sm-3 col-form-label">Username</label>
        <div class="col-sm-6">
         <input  type="text" class="form-control" name="username" value="@Model.employeeInfo.Username"/>
        </div>
    </div>
    <div  class="row mb-3">
        <label class="col-sm-3 col-form-label">PasswordStrength</label>
        <div class="col-sm-6">
            <select  class="form-control" name="passwordStrength" >
                <option value="0" >options</option>
                <option value="1" >Low</option>
                <option value="2" >Medium</option>
                <option value="3" > High</option>
            </select>
        </div>  
    </div>
     <div class="row mb-3">
        <label class="col-sm-3 col-form-label">Password</label>
        <div class="col-sm-6">
         <input  type="text" class="form-control" name="password" value="@Model.employeeInfo.Password"/>
        </div>
    </div>

    @if (Model.successMessage.Length > 0)
    {
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
                <strong>@Model.successMessage</strong>
                <button type="button" class="btn-close" data-bs-dismiss="" aria-label="close"></button>
        </div>
    }

    <div class="row mb-3">
        <div class="offset-sm-3 col-sm-3 d-grid">
            <button type="submit" class="btn btn-primary">submit</button>
        </div>
        <div class="col-sm-3 d-grid">
            <a  class="btn btn-outline-primary" href="/Employees/Index" role="button">Cancel</a>
        </div>
    </div>
</form>

Employee_Management/Pages/Employees/Delete.cshtml
@page
@model Employee_Management.Pages.Employees.DeleteModel
@{
}
@if (Model.errorMessage.Length > 0)
{
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>@Model.errorMessage</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="" aria-label="close"></button>
            </div>
}

@if (Model.successMessage.Length > 0)
{
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        <strong>@Model.successMessage</strong>
                        <button type="button" class="btn-close" data-bs-dismiss="" aria-label="close"></button>
                </div>
}




<!-- Button trigger modal -->
@*<a class='btn btn-primary btn-sm' data-bs-toggle="modal" data-bs-target="#deleteEmployee">Delete Employee</a>*@

<!-- Modal -->
@*<div class="modal fade" id="deleteEmployee">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title">Delete Employee</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <h3>Are you sure you want to delete this employee?</h3>
      </div>
      <div class="modal-footer">
          <div class="btn-group">
               <a  class="btn btn-outline-primary" href="/Employees/Delete" role="button">Delete</a>
               <a  class="btn btn-danger" href="/Employees/Index" role="button">Cancel</a>
          </div>
      </div>
    </div>
  </div> 
</div>*@

Employee_Management/Pages/Employees/Index.cshtml
@page
@model Employee_Management.Pages.Employees.IndexModel
@{
}

<br />
<h2>List of LoginDetails of Employees</h2>
<a class='btn btn-primary btn-sm'  href='/Employees/Create'>New Employee</a>


@*<button type="button" class="btn btn-primary" data-bs-toggle="ajax-modal" data-bs-target="#createEmployeeModal" data-bs-url="@Url.Page("/Employees/Create")">Register new employee</button>
<div id="PlaceHolderForModal"></div>*@


<table class="table">
    <thead>
        <tr>
           @* <th>Id</th> *@
            <th>EmployeeNo</th>
            <th>Name</th>
            <th>Email</th>
            <th>UserName</th>
            <th>Password</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model.ListEmployees)
        {
            <tr>
                    @*<td>@item.Id</td>*@
                    <td>@item.EmployeeNo</td>
                    <td>@item.Name</td>
                    <td>@item.Email</td>
                    <td>@item.Username</td>
                    <td>@item.Password</td>
                    <td>
                      @*  <button type="button" class="btn btn-primary" data-bs-toggle="ajax-modal" data-bs-target="#UpdateEmployeeModal">Edit</button>*@
                           <a class='btn btn-primary btn-sm' href='/Employees/Edit?Id=@item.Id'>Edit</a>
                           <a class='btn btn-danger btn-sm' href='/Employees/Delete?Id=@item.Id'>Delete</a>
                    </td>
            </tr>
        }     
    </tbody>
</table>



      @* Model to Update Employee *@

<div class="modal fade" id="UpdateEmployeeModal" tabindex="-1" aria-labelledby="UpdateEmployeeModallabel">
    <div class="modal-dialog">
        <form method="Post" asp-page-handler="UpdateEmployee">
            <input type="hidden" asp-for="EmployeeInfo.Id">
            <input type="hidden" asp-for="EmployeeInfo.EmployeeNo">

            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="UpdateEmployeeModallabel">Update Employee</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <!--code between forms is submitted only-->
                    <div class="mb-3">
                        <label class="form-label">Name of Employee</label>
                        <input type="text" class="form-control" asp-for="EmployeeInfo.Name" id="employeenameupdate" required />  
                    </div>    

                     <div class="mb-3">
                        <label class="form-label">Email of Employee</label>
                        <input type="text" class="form-control" asp-for="EmployeeInfo.Email" id="employeeemailupdate" required />
                    </div> 
                     <div class="mb-3">
                        <label class="form-label">UserName of Employee</label>
                        <input type="text" class="form-control" asp-for="EmployeeInfo.Username" id="employeeusernameupdate" required />
                    </div> 

                    <div class="mb-3">
                        <label class="form-label">Password of Employee</label>
                        <input type="text" class="form-control" asp-for="EmployeeInfo.Password" id="employeepasswordupdate" required />
                    </div> 
               </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>

            </div>
        </form>     
  </div>
</div>



   @*Model to Delete Employee*@

   <div class="modal fade" id="DeleteEmployeeModal" tabindex="-1" aria-labelledby="DeleteEmployeeModallabel">
    <div class="modal-dialog">
        <form method="Post" asp-page-handler="DeleteEmployee">
            <input type="hidden" asp-for="EmployeeInfo.Id">

            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="DeleteEmployeeModallabel">Delete Employee</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <!--code between forms is submitted only-->
                    <div class="mb-3">
                        <h3>Are you sure you want to delete this employee?</h3>
                    </div>    
               </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Delete</button>
                </div>

            </div>
        </form>     
  </div>
</div>


@section Scripts
    {
       @* <script>
                var myModalEl = document.getElementById('UpdateEmployeeModal')
            myModalEl.addEventListener('shown.bs.modal', function (e) 
           {
                var Id = $(e.relatedTarget).data('Id');
                    $('#EmployeeInfo.Id').val(Id); 

                    var EmployeeNo = $(e.relatedTarget).data('EmployeeNo');
                    $('#EmployeeInfo.EmployeeNo').val(EmployeeNo); 

                    var Name = $(e.relatedTarget).data('Name');
                   $('#employeenameupdate').val(Name); 
                   
                    var Email = $(e.relatedTarget).data('Email');
                   $('#employeeemailupdate').val(Email);   

                    var UserName = $(e.relatedTarget).data('UserName');
                   $('#employeeusernameupdate').val(UserName);   
                   
                    var Password = $(e.relatedTarget).data('Password');
                   $('#employeepasswordupdate').val(Password);   
                          
          })
        </script> *@


       @* <script>
                // JavaScript
                var editButtons = document.querySelectorAll(".btn-primary");

                editButtons.forEach(function(button) {
                    button.addEventListener("click", function() {
                        var row = this.closest("tr");
                        var employeeNo = row.querySelector("td:nth-child(1)").textContent;
                        var name = row.querySelector("td:nth-child(2)").textContent;
                        var email = row.querySelector("td:nth-child(3)").textContent;
                        var username = row.querySelector("td:nth-child(4)").textContent;
                        var password = row.querySelector("td:nth-child(5)").textContent;
                        var nameInput = document.querySelector("#employeenameupdate");
                        var emailInput = document.querySelector("#employeeemailupdate");
                        var usernameInput = document.querySelector("#employeeusernameupdate");
                        var passwordInput = document.querySelector("#employeepasswordupdate");

                        var updateModal = new bootstrap.Modal(document.getElementById("UpdateEmployeeModal"));
                        updateModal.show();

                        nameInput.value = name;
                        emailInput.value = email;
                        usernameInput.value = username;
                        passwordInput.value = password;
                    });
                });

        </script>*@
 }